apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-inventory-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.6"
  ACCOUNT: "az:e5240c8f-ec4f-4bd4-a36e-1981d27dd8e1"
  APP_NAME: "go-inventory.az1d-aks-architecture"
  PORT: "7000"
  ENV: "dev"

  DB_HOST: "db-az1-arch-01.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "debug" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "az1d-aks-architecture-otel-collector.default.svc.cluster.local:4317"

  OTEL_METRICS: "false"
  
  OTEL_TRACES: "true"
  OTEL_STDOUT_TRACER: "false"

  # the features below works only for a local machine, for kubernetes all logs are shipping via a collector
  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/dock/aks/az1d-aks-architecture/test-a/go-inventory"